version: '3'
services:
  api:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    command: uvicorn app.run:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mohan
      - POSTGRES_DB=python_learning
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-db:

